
17/11/2020 04:28:55 PM: DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x0334F1F0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
17/11/2020 04:28:55 PM: INFO [conexion.py:32] <connection object at 0x0334F1F0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
17/11/2020 04:33:00 PM: DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x0307F1F0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
17/11/2020 04:33:00 PM: INFO [conexion.py:45] <connection object at 0x0307F1F0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
17/11/2020 04:33:00 PM: DEBUG [conexion.py:36] Se abrio el cursor con exito: <cursor object at 0x016649A8; closed: 0>
17/11/2020 04:33:00 PM: INFO [conexion.py:46] <cursor object at 0x016649A8; closed: 0>
17/11/2020 04:41:52 PM: DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x03EEF1F0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
17/11/2020 04:41:52 PM: INFO [conexion.py:61] <connection object at 0x03EEF1F0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
17/11/2020 04:41:52 PM: DEBUG [conexion.py:36] Se abrio el cursor con exito: <cursor object at 0x024D69A8; closed: 0>
17/11/2020 04:41:52 PM: INFO [conexion.py:62] <cursor object at 0x024D69A8; closed: 0>
17/11/2020 04:42:05 PM: DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x0331F1F0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
17/11/2020 04:42:05 PM: INFO [conexion.py:61] <connection object at 0x0331F1F0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
17/11/2020 04:42:05 PM: DEBUG [conexion.py:36] Se abrio el cursor con exito: <cursor object at 0x019169A8; closed: 0>
17/11/2020 04:42:05 PM: INFO [conexion.py:62] <cursor object at 0x019169A8; closed: 0>
17/11/2020 04:42:05 PM: DEBUG [conexion.py:56] Se han cerrado los objetos de conexion y cursor 
